[package]
name = "mtpcopy"
version = "0.1.0"
authors = ["Iwasa Kazmi <kzmizzz@gmail.com>"]
edition = "2018"

[dependencies]
bindings = { package="wpd_bindings", path = "bindings" }
futures = "0.3"
chrono = "0.4"
# log = "0.4"
# pretty_env_logger = "0.4"

[dev-dependencies]
test-case = "1.1"
