fn main() {
    windows::build!(
        Windows::Win32::Devices::PortableDevices::{
            IEnumPortableDeviceObjectIDs,
            IPortableDevice,
            IPortableDeviceContent,
            IPortableDeviceDataStream,
            IPortableDeviceKeyCollection,
            IPortableDeviceManager,
            IPortableDeviceProperties,
            IPortableDevicePropVariantCollection,
            IPortableDeviceResources,
            IPortableDeviceValues,
            PortableDevice,
            PortableDeviceKeyCollection,
            PortableDeviceManager,
            PortableDevicePropVariantCollection,
            PortableDeviceValues,
            DELETE_OBJECT_OPTIONS,
        },
        Windows::Win32::Foundation::{
            CloseHandle,
            BOOL,
            FILETIME,
            HANDLE,
            PWSTR,
            SYSTEMTIME,
            S_OK,
        },
        Windows::Win32::Storage::FileSystem::{
            CreateFileW,
            SetFileTime,
            FILE_FLAGS_AND_ATTRIBUTES,
            FILE_ACCESS_FLAGS,
            FILE_SHARE_MODE,
            FILE_CREATION_DISPOSITION,
        },
        Windows::Win32::Storage::StructuredStorage::{
            IStream,
            STGC,
            PROPVARIANT
        },
        Windows::Win32::System::Com::{
            CoTaskMemFree,
        },
        Windows::Win32::System::Time::{
            SystemTimeToFileTime,
        },
        Windows::Win32::System::PropertiesSystem::{
            PROPERTYKEY,
        },
    );
}
