fn main() {
    windows::build!(
        windows::win32::com::{
            CoInitialize, CoCreateInstance, CoTaskMemFree, CLSCTX,
        },
        windows::win32::file_system::CreateFileW,
        windows::win32::file_system::FILE_ACCESS_FLAGS,
        windows::win32::file_system::FILE_CREATE_FLAGS,
        windows::win32::file_system::FILE_FLAGS_AND_ATTRIBUTES,
        windows::win32::file_system::FILE_SHARE_FLAGS,
        windows::win32::structured_storage::{IStream, STGC},
        windows::win32::system_services::HANDLE,
        windows::win32::windows_portable_devices::{
            IEnumPortableDeviceObjectIDs,
            IPortableDevice,
            IPortableDeviceContent,
            IPortableDeviceDataStream,
            IPortableDeviceKeyCollection,
            IPortableDeviceManager,
            IPortableDeviceProperties,
            IPortableDevicePropVariantCollection,
            IPortableDeviceResources,
            IPortableDeviceValues,
            PortableDevice,
            PortableDeviceKeyCollection,
            PortableDeviceManager,
            PortableDevicePropVariantCollection,
            PortableDeviceValues,
        },
        windows::win32::windows_programming::CloseHandle,
        windows::win32::windows_programming::FILETIME,
        windows::win32::windows_programming::SetFileTime,
        windows::win32::windows_programming::SYSTEMTIME,
        windows::win32::windows_programming::SystemTimeToFileTime,
        windows::win32::windows_properties_system::PROPERTYKEY,
    );
}
