fn main() {
    windows::build!(
        Windows::Win32::System::Com::{
            CoInitialize, CoCreateInstance, CoTaskMemFree, CLSCTX_INPROC_SERVER,
        },
        Windows::Win32::Storage::FileSystem::{
            CreateFileW,
            FILE_ATTRIBUTE_NORMAL,
            FILE_GENERIC_READ,
            FILE_GENERIC_WRITE,
            FILE_SHARE_NONE,
            OPEN_EXISTING,
        },
        Windows::Win32::Storage::StructuredStorage::{
            IStream, STGC_DEFAULT, PROPVARIANT
        },
        Windows::Win32::System::SystemServices::{S_OK},
        Windows::Win32::Devices::PortableDevices::{
            IEnumPortableDeviceObjectIDs,
            IPortableDevice,
            IPortableDeviceContent,
            IPortableDeviceDataStream,
            IPortableDeviceKeyCollection,
            IPortableDeviceManager,
            IPortableDeviceProperties,
            IPortableDevicePropVariantCollection,
            IPortableDeviceResources,
            IPortableDeviceValues,
            PortableDevice,
            PortableDeviceKeyCollection,
            PortableDeviceManager,
            PortableDevicePropVariantCollection,
            PortableDeviceValues,
            PORTABLE_DEVICE_DELETE_WITH_RECURSION,
        },
        Windows::Win32::System::WindowsProgramming::{
            CloseHandle,
            SetFileTime,
            SystemTimeToFileTime,
        },
        Windows::Win32::System::PropertiesSystem::{PROPERTYKEY},
    );
}
